import CreateFakeOrders from "./CreateFakeOrders.jsx";

export default function FakeData() {
  return (
    <>
      <div class="w3-container" style={{ width: "60%", margin: "auto" }}>
        <h1 class="w3-center w3-text-grey">Autogenerated fake data</h1>
        <CreateFakeOrders />
      </div>
    </>
  );
}
